### ISSUE TITLE
Perfect Forward Secrecy

### ISSUE THREAD

**Issue by dahjelle** [mikemaccana/ssl-config#2]
Is using an intermediate or modern cipher suite sufficient for perfect forward secrecy? Or is some other configuration necessary?

I don't necessarily think this is related to this module, but I'm digging into why Chrome is showing an "obsolete cryptography" warning for my Node.js web site. Since I'm using `ssl-config`, I thought I'd ask briefly here. Feel free to close without responding if you want since this is rather out of scope. :-D

```
var server_config = require('./server_config.json');
var sslConfig = require('ssl-config')('intermediate');
...
server.connection({
  host: server_config.server.host,
  port: server_config.server.port,
  tls: {
    key: fs.readFileSync(server_config.tls.key),
    cert: fs.readFileSync(server_config.tls.cert),
    ciphers: sslConfig.cipherSuites,
    honorCipherOrder: true, // as per http://nodejs.org/api/tls.html
    secureOptions: sslConfig.minimumTLSVersion
  }
});
```

While Chrome shows green, clicking on the lock icon to get more information shows "Your connection to example.com is encrypted with obsolete cryptography.” as [described here](https://www.chromium.org/Home/chromium-security/education/tls#TOC-Deprecation-of-TLS-Features-Algorithms-in-Chrome). I get this using either the "intermediate" or "modern" cipher suites.

That page says:

> This means that the connection to the current website is using an outdated cipher suite (which Chrome still allows if the server insists on it).
> 
> In order for the message to indicate “modern cryptography”, the connection should use forward secrecy and either AES-GCM or CHACHA20_POLY1305. Other cipher suites are known to have weaknesses. Most servers will wish to negotiate TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256.

While there are a lot of descriptions of forward secrecy around, I'm having a tough time finding ones that what is necessary for its implementation in Node.

Any insights/links for more info appreciated!

(P.S. Thanks again for the module. Glad to be using it!)

**Comment by dahjelle** [comment]
I think I found my answer. To enable perfect forward secrecy, you need to have the `dhparams` option set to a file generated by `openssl dhparam -out outfile.pem 2048`. Unfortunately, as far as I can tell, this option isn't supported in Node.js 0.10.x, so I've not been able to test it. Perhaps it is worth adding to the docs nonetheless?

(One other part of the answer was that I was using `sslConfig.cipherSuites` in the above code, rather than `sslConfig.ciphers`. Pull request #3 should fix the README to prevent that. ;-)

**Comment by mikemaccana** [comment]
Yep, you need node 0.12 for EC modes. I'll make that more obvious in the README.
